# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rootprofile',
            name='quote',
            field=models.CharField(default='', max_length=140),
        ),
    ]
