# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='bg',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
