# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='bg_thread',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
